# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42e30a0a60f8fbab086c21fc0b2698e381deb069ba4d484e886bf8758e5c393c90bc228eb0f46362187042bad82cbad429381c716a6f22e7268d0291ac5d4e5a

test:
  secret_key_base: 954691426e92ed4f89d2ec0cefe94b54b4fc25a6dbdda5dd6dfe477d2334c32ec18ab534a2bb8b1b88a7a1e78461a0877994f5c4c200814fd9f444c3d9473ddb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
